# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-03 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Houzz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phome', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('oblast', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'parce_houzz',
            },
        ),
    ]
