# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-03 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='houzz',
            name='siteUrl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='houzz',
            name='name',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='houzz',
            name='oblast',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AlterField(
            model_name='houzz',
            name='phome',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
