# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-03 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20180103_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houzz',
            old_name='phome',
            new_name='phone',
        ),
    ]
