# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-05 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_eshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshop',
            name='edit',
            field=models.BooleanField(default=False),
        ),
    ]
