# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-17 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_eshop_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myremont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=90, null=True)),
                ('site', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'db_table': 'parce_myremont',
            },
        ),
    ]
