# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_myremont'),
    ]

    operations = [
        migrations.AddField(
            model_name='eshop',
            name='newcol',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
