# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-07 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20180206_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='myremont',
            name='type_q',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
