# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-12 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_myremont_type_q'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.CharField(blank=True, max_length=90, null=True)),
                ('img_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'img_watch',
            },
        ),
    ]
