# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='img_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
