# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-13 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_priceattr_watchprice'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='priceattr',
            table='price_attr',
        ),
    ]
