# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-13 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_auto_20180213_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchprice',
            name='attributes',
        ),
        migrations.DeleteModel(
            name='PriceAttr',
        ),
        migrations.DeleteModel(
            name='WatchPrice',
        ),
    ]
