# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-13 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20180213_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'price_attr',
            },
        ),
        migrations.CreateModel(
            name='WatchPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=45)),
                ('url_img_price', models.CharField(blank=True, max_length=255, null=True)),
                ('url_imgs', models.CharField(blank=True, max_length=255, null=True)),
                ('attributes', models.ManyToManyField(related_name='group_clients', to='company.PriceAttr')),
            ],
            options={
                'db_table': 'watch_price',
            },
        ),
    ]
