# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-21 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_watchprice_type_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchprice',
            name='del_data',
            field=models.BooleanField(default=False),
        ),
    ]
