# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-03-22 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_watchprice_del_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
